### ISSUE TITLE
So badly written.

### ISSUE THREAD

**Issue by Syntaxious** [TheAppleGamer/KickDeath#1]
It's actually so bad, the instance kick doesn't exist, Mr TheAppleGamer.

**Comment by Syntaxious** [comment]
Here, let me fix it for you. I'll open a PR.

**Comment by TheAppleGamer** [comment]
I don't know why you are doing this... You one minute attack me and next minute you help

**Comment by TheAppleGamer** [comment]
But to say, it did kick the player on death. I've tested this
